version: '3'
services:
  webserver:
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - '8081:80'

  app:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www

  db:
    image: mariadb:10.3
    ports:
      - '33061:3306'
    volumes:
      - ./.docker/dbdata/mysql:/var/lib/database
    environment:
      MYSQL_DATABASE: ibnuisdev
      MYSQL_ROOT_PASSWORD: toor

  redis:
    image: redis
    volumes:
      - ./.docker/dbdata/redis:/data
