version: '3'
services:
  webserver:
    image: 'nginx:alpine'
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - './:/var/www'
      - './.docker/nginx/conf.d:/etc/nginx/conf.d/'
    networks:
      - ibnuisdev
    depends_on:
      - app
      - db
      - redis
  app:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - './:/var/www'
    working_dir: '/var/www'
    networks:
      - ibnuisdev
  db:
    image: 'mariadb:10.3'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'ibnuisdev_db:/var/lib/database'
    networks:
      - ibnuisdev
  dbtest:
    image: 'mariadb:10.3'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}_test'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'ibnuisdev_dbtest:/var/lib/database'
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'ibnuisdev_redis:/data'
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
        - '${FORWARD_MAILHOG_PORT:-1025}:1025'
        - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
        - ibnuisdev
networks:
  ibnuisdev:
    driver: bridge
volumes:
  ibnuisdev_db:
    driver: local
  ibnuisdev_dbtest:
    driver: local
  ibnuisdev_redis:
    driver: local