version: '3'
services:
  webserver:
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - '8081:80'

  app:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www

  db:
    image: mariadb:10.3
    ports:
      - '33061:3306'
    volumes:
      - ./.docker/dbdata/mysql:/var/lib/database
    environment:
      MYSQL_DATABASE: ibnuisdev
      MYSQL_ROOT_PASSWORD: toor

  dbtest:
    image: mariadb:10.3
    ports:
      - '33062:3306'
    tmpfs:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: ibnuisdev_test
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  redis:
    image: redis
    volumes:
      - ./.docker/dbdata/redis:/data

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./.docker/dbdata/sqlite:/root/db
